// ==UserScript==
// @name         簡易翻譯器
// @version      0.0.1
// @author       Canaan HS
// @description  高效將對應英文翻譯成繁體中文 (實驗項目)

// @match        *://yande.re/*
// @match        *://rule34.xxx/*
// @match        *://nhentai.net/*
// @match        *://konachan.com/*
// @match        *://danbooru.donmai.us/*

// @license      MIT
// @noframes
// @namespace    https://greasyfork.org/users/989635

// @run-at       document-start
// ==/UserScript==

(async function() {

    const Short_Words = {
        "no": "否",
        "by": "由",
        "to": "到",
        "or": "或",
        "yes": "是",
        "and": "和",
        "go": "執行",
        "my": "我的",
        "day": "天",
        "ago": "前",
        "tag": "標籤",
        "red": "紅色",
        "may": "五月",
        "all": "全部",
        "dls": "完成",
        "from": "從",
        "jan": "一月",
        "feb": "二月",
        "mar": "三月",
        "apr": "四月",
        "jun": "六月",
        "jul": "七月",
        "aug": "八月",
        "sep": "九月",
        "oct": "十月",
        "any": "任何",
        "days": "天",
        "year": "年",
        "hot": "熱門",
        "new": "新的",
        "old": "舊的",
        "age": "年齡",
        "legs": "腿",
        "feet": "腳",
        "none": "沒有",
        "home": "首頁",
        "news": "新聞",
        "wiki": "維基",
        "tags": "標籤",
        "misc": "雜項",
        "save": "儲存",
        "file": "檔案",
        "here": "這裡",
        "date": "日期",
        "hits": "點選",
        "june": "六月",
        "july": "七月",
        "view": "檢視",
        "nov": "十一月",
        "dec": "十二月",
        "size": "大小",
        "list": "清單",
        "sort": "排序",
        "type": "型別",
        "chat": "聊天",
        "hour": "小時",
        "month": "月",
        "years": "年",
        "info": "資訊",
        "week": "星期",
        "name": "名稱",
        "more": "更多",
        "help": "幫助",
        "weeks": "周",
        "page": "頁數",
        "note": "筆記",
        "like": "喜歡",
        "edit": "編輯",
        "post": "帖子",
        "send": "傳送",
        "user": "使用者",
        "stats": "統計",
        "front": "首頁",
        "tos": "服務條款",
        "clear": "清除",
        "title": "標題",
        "close": "關閉",
        "never": "從未",
        "power": "權重",
        "trust": "信任",
        "topic": "話題",
        "score": "分數",
        "voted": "投票",
        "march": "三月",
        "april": "四月",
        "total": "總計",
        "other": "其他",
        "basic": "基本",
        "files": "檔案",
        "pages": "頁數",
        "group": "團體",
        "mixed": "混合",
        "go to": "前往",
        "delay": "延遲",
        "flags": "標記",
        "hours": "小時",
        "order": "排序",
        "style": "樣式",
        "about": "關於",
        "store": "商店",
        "today": "今天",
        "second": "秒",
        "pools": "集合",
        "count": "數量",
        "terms": "條款",
        "months": "月",
        "using": "使用",
        "prev": "上一個",
        "next": "下一個",
        "posts": "貼文",
        "forum": "論壇",
        "login": "登入",
        "notes": "筆記",
        "likes": "喜歡",
        "share": "分享",
        "reply": "回覆",
        "block": "封鎖",
        "sent": "已傳送",
        "media": "媒體",
        "image": "圖片",
        "video": "影片",
        "audio": "音訊",
        "guest": "訪客",
        "theme": "主題",
        "users": "使用者",
        "forums": "論壇",
        "search": "搜尋",
        "cancel": "取消",
        "delete": "刪除",
        "normal": "普通",
        "global": "全球",
        "status": "狀態",
        "online": "線上",
        "amount": "金額",
        "visits": "訪問",
        "august": "八月",
        "added": "已新增",
        "manage": "管理",
        "common": "常用",
        "others": "其他",
        "always": "總是",
        "parent": "家長",
        "rating": "評分",
        "enable": "啟用",
        "hidden": "隱藏",
        "reason": "原因",
        "events": "事件",
        "seconds": "秒",
        "circle": "圈子",
        "faults": "故障",
        "action": "操作",
        "select": "選擇",
        "series": "系列",
        "active": "活躍",
        "groups": "團體",
        "random": "隨機",
        "invert": "反選",
        "export": "匯出",
        "medium": "中等",
        "absurd": "荒謬",
        "source": "來源",
        "option": "選項",
        "change": "變化",
        "upload": "上傳",
        "report": "舉報",
        "saved": "已儲存",
        "follow": "關注",
        "logout": "登出",
        "signup": "註冊",
        "images": "圖片",
        "videos": "影片",
        "audios": "音訊",
        "admin": "管理員",
        "member": "成員",
        "themes": "主題",
        "public": "公開",
        "create": "建立",
        "update": "更新",
        "remove": "移除",
        "liked": "已喜歡",
        "artist": "繪師",
        "height": "身高",
        "weight": "體重",
        "gender": "性別",
        "client": "客戶",
        "watched": "關注",
        "popular": "熱門",
        "uploads": "上傳",
        "private": "私人",
        "confirm": "確定",
        "quality": "品質",
        "version": "版本",
        "offline": "離線",
        "healthy": "健康",
        "comment": "評論",
        "ranking": "排行",
        "january": "一月",
        "october": "十月",
        "posted": "已發布",
        "publish": "發布",
        "between": "介於",
        "visible": "可見",
        "default": "預設",
        "sources": "來源",
        "succeed": "成功",
        "country": "國家",
        "instead": "代替",
        "appeals": "申訴",
        "aliases": "別名",
        "general": "一般",
        "minutes": "分鐘",
        "privacy": "隱私",
        "upgrade": "升級",
        "contact": "聯絡",
        "gallery": "相簿",
        "disable": "停用",
        "history": "歷史",
        "listing": "清單",
        "options": "選項",
        "changes": "改變",
        "setting": "設定",
        "email": "電子郵件",
        "shared": "已分享",
        "replies": "回覆",
        "edited": "已編輯",
        "message": "訊息",
        "receive": "接收",
        "mention": "提到",
        "content": "內容",
        "viewed": "已檢視",
        "recent": "最近的",
        "banned": "被禁止",
        "artists": "繪師",
        "go back": "返回",
        "sign in": "登入",
        "rename": "重新命名",
        "toplists": "排行",
        "bounties": "懸賞",
        "overview": "概況",
        "settings": "設定",
        "minimal": "最小化",
        "created": "已建立",
        "hitrate": "命中率",
        "february": "二月",
        "creator": "創作者",
        "comments": "評論",
        "continue": "繼續",
        "advanced": "進階",
        "feedback": "反饋",
        "rejected": "拒絕",
        "approved": "批准",
        "language": "語言",
        "download": "下載",
        "related": "有關的",
        "register": "註冊",
        "deleted": "已刪除",
        "parodies": "出處",
        "category": "類別",
        "password": "密碼",
        "blocked": "已封鎖",
        "dislike": "不喜歡",
        "follower": "粉絲",
        "messages": "訊息",
        "mentions": "提到",
        "trending": "趨勢",
        "updated": "已更新",
        "removed": "已移除",
        "replied": "已回覆",
        "rewrite": "重新改寫",
        "donations": "捐贈",
        "advertise": "廣告",
        "uploader": "上傳者",
        "coverage": "覆蓋率",
        "september": "九月",
        "november": "十一月",
        "december": "十二月",
        "timestamp": "時間",
        "expunged": "已刪除",
        "completes": "完成",
        "reclass": "重新分類",
        "approvals": "批准",
        "ascending": "升序",
        "metadata": "元數據",
        "character": "角色",
        "sensitive": "敏感",
        "pending": "等待處理",
        "copyright": "版權",
        "resized": "調整大小",
        "approver": "審核人",
        "uploaded": "已上傳",
        "languages": "語言",
        "favorite": "收藏夾",
        "profile": "個人資料",
        "followers": "粉絲",
        "reported": "已舉報",
        "received": "已接收",
        "verified": "已驗證",
        "unblock": "解除封鎖",
        "searched": "已搜尋",
        "moderator": "版主",
        "inactive": "不活躍",
        "expunging": "刪除",
        "thumbnail": "縮圖",
        "extended": "擴充套件",
        "favorites": "收藏夾",
        "metadatas": "元數據",
        "moderation": "管理",
        "descending": "降序",
        "characters": "人物",
        "categories": "類別",
        "commentary": "評論",
        "unfollow": "取消關注",
        "dashboard": "儀錶板",
        "disliked": "已不喜歡",
        "commented": "已評論",
        "translated": "翻譯",
        "path name": "路徑名",
        "username": "使用者名稱",
        "published": "釋出時間",
        "namespace": "命名空間",
        "information": "資訊",
        "past month": "月排行",
        "file size": "檔案大小",
        "discussions": "討論",
        "description": "描述",
        "recommended": "推薦",
        "following": "正在關注",
        "downloaded": "已下載",
        "safe mode": "安全模式",
        "compilation": "編輯",
        "processing": "正在處理",
        "page links": "頁面連結",
        "downloading": "下載中",
        "implications": "影響",
        "replacements": "替換",
        "notification": "通知",
        "verification": "驗證",
        "disapprovals": "不批准",
        "questionable": "不確定",
        "notifications": "通知"
    };

    const Long_Words = {
        "my tags": "我的標籤",
        "file name": "檔名",
        "front page": "首頁",
        "my stats": "我的統計",
        "select all": "全選",
        "tag name": "標籤名稱",
        "all time": "全部時間",
        "tag group": "標籤群組",
        "max speed": "最大速度",
        "post tags": "釋出標籤",
        "last seen": "最後線上於",
        "source code": "原始碼",
        "new gallery": "新相簿",
        "the keyword": "關鍵詞",
        "date added": "新增時間",
        "learn more": "瞭解更多",
        "contact us": "聯絡我們",
        "my account": "我的帳戶",
        "my settings": "我的設定",
        "file search": "檔案搜尋",
        "new tagset": "新建標籤集",
        "daily stats": "每日統計",
        "auto paused": "自動暫停",
        "force abort": "強制中止",
        "date posted": "釋出時間",
        "pages range": "頁面範圍",
        "total count": "總共數量",
        "other sites": "其他網站",
        "popular now": "現在熱門",
        "new uploads": "最新上傳",
        "add new tag": "新增新標籤",
        "post comment": "發表評論",
        "view gallery": "瀏覽相簿",
        "confirm move": "確認移動",
        "yearly stats": "年度統計",
        "time created": "建立時間",
        "time updated": "更新時間",
        "back to list": "返回列表",
        "all torrents": "全部種子",
        "close window": "關閉視窗",
        "gallery list": "相簿列表",
        "folder name": "資料夾名稱",
        "save changes": "儲存更改",
        "text cleaned": "去除文字",
        "upload files": "上傳檔案",
        "start upload": "開始上傳",
        "natural sort": "自然排序",
        "lexical sort": "字典排序",
        "force paused": "強制暫停",
        "child gallery": "子相簿",
        "mod actions": "管理員操作",
        "blacklisted": "列入黑名單",
        "related tags": "有關標籤",
        "hidden posts": "隱藏貼文",
        "img servers": "圖片伺服器",
        "find similar": "尋找類似",
        "back to index": "返回索引",
        "pending tags": "待稽核標籤",
        "display order": "顯示順序",
        "apply changes": "應用更改",
        "gallery title": "相簿標題",
        "number images": "影象編號",
        "access denied": "拒絕訪問",
        "view original": "檢視原圖",
        "no hits found": "什麼也沒有",
        "published time": "釋出時間",
        "favorited time": "收藏時間",
        "change category": "移動到",
        "not yet rated": "還沒有評分",
        "report gallery": "舉報相簿",
        "confirm delete": "確認刪除",
        "approved tags": "已批准標籤",
        "rejected tags": "已拒絕標籤",
        "submit comment": "提交評論",
        "create gallery": "建立相簿",
        "empty galleries": "空相簿",
        "create folder": "建立資料夾",
        "delete gallery": "刪除相簿",
        "revert changes": "撤銷更改",
        "current origin": "當前站點",
        "reset password": "重置密碼",
        "post a comment": "發表評論",
        "more like this": "更多類似",
        "back to gallery": "返回相簿",
        "contact poster": "聯絡評論者",
        "content warning": "內容警告",
        "vote to expunge": "投票刪除",
        "manage folders": "管理資料夾",
        "public category": "釋出類別",
        "available actions": "操作",
        "gallery folder": "相簿資料夾",
        "not created yet": "尚未建立",
        "publish gallery": "釋出相簿",
        "cancel download": "取消下載",
        "last edited on": "最後編輯於",
        "uploaded files": "上傳檔案數",
        "total filesize": "總檔案大小",
        "setting weights": "設定權重",
        "terms of service": "服務條款",
        "search keywords": "搜尋關鍵詞",
        "disable filters": "停用過濾器",
        "delete selected": "刪除選中項",
        "gallery toplists": "相簿排行",
        "tagging toplists": "標籤排行",
        "cleanup toplists": "清理排行",
        "gallery category": "相簿分類",
        "gallery language": "相簿語言",
        "download archive": "下載檔案",
        "contact uploader": "聯絡上傳者",
        "uploader comment": "上傳者評論",
        "click to show all": "顯示全部",
        "post new comment": "傳送新評論",
        "disk cache size": "磁碟快取大小",
        "new folder name": "新資料夾名稱",
        "submit application": "提交申請",
        "visitor statistics": "訪客統計",
        "resize to window": "調整視窗大小",
        "artist's commentary": "繪師的評論",
        "to post a comment.": "到帖子發表評論",
        "there are no comments.": "沒有評論",
        "tags export settings": "標籤匯出設定",
        "you are not logged in.": "你沒有登入",
        "this post is pending approval.": "這篇文章正在等待審核"
    };

    const Language = {
        "thai": "泰文",
        "dutch": "荷蘭語",
        "french": "法文",
        "german": "德語",
        "korean": "韓文",
        "czech": "捷克語",
        "greek": "希臘語",
        "hindi": "印地語",
        "latin": "拉丁語",
        "malay": "馬來語",
        "english": "英文",
        "polish": "波蘭語",
        "danish": "丹麥語",
        "chinese": "中文",
        "japanese": "日語",
        "arabic": "阿拉伯語",
        "cebuano": "宿務語",
        "finnish": "芬蘭語",
        "persian": "波斯語",
        "swedish": "瑞典語",
        "hebrew": "希伯來語",
        "russian": "俄羅斯語",
        "italian": "義大利文",
        "spanish": "西班牙語",
        "javanese": "爪哇語",
        "slovak": "斯洛伐克語",
        "tagalog": "他加祿語",
        "turkish": "烏克蘭語",
        "esperanto": "世界語",
        "norwegian": "挪威語",
        "serbian": "塞爾維亞語",
        "hungarian": "匈牙利語",
        "vietnamese": "越南語",
        "catalan": "加泰羅尼亞語",
        "romanian": "羅馬尼亞語",
        "ukrainian": "烏克蘭語",
        "estonian": "愛沙尼亞語",
        "croatian": "克羅埃西亞語",
        "portuguese": "葡萄牙文",
        "albanian": "阿爾巴尼亞語",
        "bulgarian": "保加利亞語",
        "indonesian": "西澳特羅尼西亞語"
    };

    const Artist = {
        "shuhan": "主犯",
        "kutani": "九手児",
        "zurikishi": "ずり騎士",
        "tuna empire": "まぐろ帝國",
        "rio tsukatsuki": "調月莉央",
        "chiyou yoyuchi": "千要よゆち",
        "aji ponntarou": "安治ぽん太郎",
        "miyamoto smoke": "宮本スモーク",
    };

    const Character = {
        "yumeko jabami": "蛇喰夢子",
        "midari ikishima": "蛇喰夢子",
        "belle": "鈴",
        "lucy": "露西",
        "rumia": "露米婭",
        "cirno": "琪露諾",
        "qingyi": "青衣",
        "firefly": "流螢",
        "soukaku": "蒼角",
        "zhu yuan": "朱鳶",
        "levi": "裡維·阿卡曼",
        "ellen joe": "艾蓮·喬",
        "soldier 11": "11號",
        "ben bigger": "本·比格",
        "billy kid": "比利·奇德",
        "von lycaon": "馮·萊卡恩",
        "hong meiling": "紅美鈴",
        "ink nijihara": "虹原茵可",
        "piper wheel": "派派·韋爾",
        "reimu hakurei": "博麗靈夢",
        "alexandrina": "亞歷山德麗娜",
        "hoshimi miyabi": "星見雅",
        "nekomiya mana": "貓宮又奈",
        "anby demara": "安比·德瑪拉",
        "sakuya izayoi": "十六夜咲夜",
        "corin wickes": "可琳·威克斯",
        "grace howard": "格莉絲·霍華德",
        "anton ivanov": "安東·伊萬諾夫",
        "nicole demara": "妮可·德瑪拉",
        "marisa kirisame": "霧雨魔理沙",
        "lotte no omocha": "露蒂的玩具",
        "mystia lorelei": "斯蒂婭·蘿蕾拉",
        "koleda belobog": "珂蕾妲·貝洛伯格",
        "letty whiterock": "蕾迪‧霍瓦特羅克",
        "wriggle nightbug": "莉格露·奈特巴格",
        "remilia scarlet": "蕾米莉亞‧斯卡雷特",
        "patchouli knowledge": "帕秋莉‧諾蕾姬",
    };

    const Title = {
        "kakegurui": "狂賭之淵",
        "touhou": "東方",
        "moetan": "萌單",
        "bleach": "死神",
        "saki": "天才麻將少女",
        "star rail": "星鐵",
        "kaguyuzu": "カグユヅ",
        "miki hime": "みき姫",
        "ro-kyu-bu": "蘿球社",
        "umamusume": "賽馬娘",
        "azurlane": "碧藍航線",
        "arknights": "明日方舟",
        "azur lane": "碧藍航線",
        "azur_lane": "碧藍航線",
        "eldenring": "艾爾登法環",
        "genshinimpact": "原神",
        "elden ring": "艾爾登法環",
        "elden_ring": "艾爾登法環",
        "bluearchive": "蔚藍檔案",
        "date a live": "約會大作戰",
        "genshin impact": "原神",
        "genshin_impact": "原神",
        "wutheringwaves": "鳴潮",
        "blue archive": "蔚藍檔案",
        "blue_archive": "蔚藍檔案",
        "wuthering waves": "鳴潮",
        "wuthering_waves": "鳴潮",
        "sword art online": "刀劍神域",
        "strawberry panic": "草莓狂熱",
        "zenless zone zero": "絕區零",
        "zenless_zone_zero": "絕區零",
        "kantaicollection": "艦隊收藏",
        "kantai collection": "艦隊收藏",
        "kantai_collection": "艦隊收藏",
        "touhou project": "東方Project",
        "honkai: star rail": "崩壞：星穹鐵道",
        "puella magi madoka magica": "魔法少女小圓",
        "goddess of victory: nikke": "勝利女神：妮姬",
        "boku wa tomodachi ga sukunai": "我的朋友很少",
        "ore no imouto ga konna ni kawaii wake ga nai": "我的妹妹不可能那麼可愛",
    };

    const Beautify = {
        "3d": "3D",
        "fate": "Fate",
        "vocaloid": "V 家",
        "hololive": "Holo Live!",
        "fate/grand order": "FGO",
        "fate grand order": "FGO",
        "love live": "Love Live!",
    };

    const Tags = {
        "cat": "貓",
        "dog": "狗",
        "oni": "鬼",
        "pig": "豬",
        "cow": "牛",
        "ass": "屁股",
        "bear": "熊",
        "eel": "鰻魚",
        "elf": "精靈",
        "fish": "魚",
        "fox": "狐狸",
        "nun": "修女",
        "wolf": "狼",
        "orc": "獸人",
        "sex": "性愛",
        "crab": "螃蟹",
        "huge": "巨大",
        "vore": "吞入",
        "loli": "蘿莉",
        "bbm": "胖男人",
        "bbw": "胖女人",
        "gag": "塞口器",
        "hood": "兜帽",
        "tail": "尾巴",
        "anal": "肛交",
        "aunt": "阿姨",
        "bull": "公牛",
        "dilf": "大叔",
        "eggs": "生蛋",
        "frog": "青蛙",
        "goat": "山羊",
        "guro": "獵奇",
        "horse": "馬",
        "lion": "獅子",
        "maid": "女僕",
        "miko": "巫女",
        "mute": "啞巴",
        "rape": "強姦",
        "slug": "蛞蝓",
        "snake": "蛇",
        "tube": "管子",
        "whip": "鞭打",
        "worm": "蟲子",
        "scar": "刀疤",
        "nazi": "納粹",
        "milf": "熟女",
        "scat": "排洩",
        "halo": "光環",
        "bald": "禿頭",
        "bdsm": "SM",
        "blood": "血",
        "sheep": "羊",
        "doll": "玩偶",
        "male": "男性",
        "body": "身體",
        "skin": "皮膚",
        "head": "頭部",
        "eyes": "眼睛",
        "nose": "鼻子",
        "neck": "脖子",
        "arms": "手臂",
        "mouth": "嘴",
        "small": "小的",
        "large": "大的",
        "horns": "洞角",
        "uncle": "叔叔",
        "comic": "漫畫",
        "clone": "克隆",
        "leash": "狗頸",
        "angel": "天使",
        "apron": "圍裙",
        "birth": "分娩",
        "blind": "瞎子",
        "bride": "新娘",
        "camel": "駱駝",
        "cbt": "蹂躪陰莖",
        "clamp": "夾子",
        "clown": "小丑",
        "coach": "教練",
        "crown": "皇冠",
        "dragon": "龍",
        "drugs": "藥物",
        "enema": "灌腸",
        "fairy": "仙女",
        "furry": "毛皮",
        "ghost": "鬼魂",
        "giant": "巨人",
        "harem": "後宮",
        "hijab": "頭巾",
        "kappa": "河童",
        "mouse": "老鼠",
        "novel": "小說",
        "ryona": "虐待",
        "shark": "鯊魚",
        "tiger": "老虎",
        "whale": "鯨魚",
        "widow": "寡婦",
        "zebra": "斑馬",
        "wings": "翅膀",
        "slave": "奴隸",
        "snuff": "殺害",
        "nurse": "護士",
        "witch": "女巫",
        "tutor": "家教",
        "niece": "侄女",
        "ninja": "忍者",
        "dougi": "道服",
        "slime": "粘液",
        "tiara": "頭飾",
        "x-ray": "透視",
        "demon": "惡魔",
        "oouso": "大噓",
        "chest": "乳房",
        "torso": "軀幹",
        "penile": "屌",
        "tools": "工具",
        "semen": "精液",
        "force": "力量",
        "drunk": "喝醉",
        "hairy": "多毛",
        "sound": "有聲音",
        "oil": "油覆蓋皮膚",
        "donkey": "毛驢",
        "vomit": "嘔吐物",
        "mature": "成熟",
        "priest": "牧師",
        "makeup": "濃妝",
        "non-h": "無色情",
        "crying": "哭泣",
        "gloves": "手套",
        "afro": "非洲爆炸頭",
        "braces": "牙套",
        "butler": "管家",
        "catboy": "貓男",
        "chikan": "痴漢",
        "collar": "項圈",
        "cousin": "亂倫",
        "diaper": "尿布",
        "father": "父親",
        "gokkun": "飲精",
        "how to": "教程",
        "insect": "昆蟲",
        "kimono": "和服",
        "latex": "乳膠衣",
        "legjob": "腿交",
        "maggot": "蛆蟲",
        "monkey": "猴子",
        "muscle": "肌肉",
        "rabbit": "兔子",
        "redraw": "重繪",
        "robot": "機器人",
        "saliva": "唾液",
        "sample": "樣本",
        "spider": "蜘蛛",
        "turtle": "烏龜",
        "twins": "雙胞胎",
        "zombie": "喪屍",
        "rimjob": "舔肛",
        "midget": "侏儒",
        "mother": "母親",
        "pirate": "海盜",
        "incest": "亂倫",
        "goblin": "地精",
        "smell": "嗅氣味",
        "inseki": "姻親",
        "alien": "外星人",
        "yukata": "浴衣",
        "parody": "出處",
        "animal": "動物",
        "fluids": "流體",
        "waste": "排洩物",
        "absorb": "融合",
        "manga": "漫畫雜誌",
        "female": "女性",
        "breasts": "乳房",
        "harpy": "鳥身女妖",
        "assjob": "屁股交",
        "merman": "人魚男",
        "hanging": "絞刑",
        "defaced": "損壞",
        "mesuiki": "男娘",
        "ahegao": "阿黑顏",
        "albino": "白化病",
        "amputee": "殘肢",
        "artbook": "畫集",
        "bikini": "比基尼",
        "bondage": "束縛",
        "brother": "兄弟",
        "bukkake": "顏射",
        "burping": "打嗝",
        "catgirl": "貓女",
        "condom": "避孕套",
        "dog boy": "犬男",
        "dolphin": "海豚",
        "farting": "放屁",
        "filming": "拍攝",
        "fisting": "拳交",
        "footjob": "足交",
        "fox boy": "狐男",
        "gorilla": "猩猩",
        "handjob": "手淫",
        "harness": "馬具",
        "kissing": "接吻",
        "monster": "怪物",
        "octopus": "章魚",
        "ostrich": "鴕鳥",
        "paizuri": "乳交",
        "pillory": "刑具",
        "shemale": "人妖",
        "tights": "緊身服",
        "vacbed": "真空床",
        "waiter": "服務員",
        "yandere": "病嬌",
        "smegma": "包皮垢",
        "pasties": "乳貼",
        "tomboy": "假小子",
        "monoeye": "獨眼",
        "ssbbm": "超級肥男",
        "ssbbw": "超級肥女",
        "steward": "管家",
        "torture": "酷刑",
        "pig man": "豬男",
        "sockjob": "襪交",
        "shibari": "繩縛",
        "milking": "擠奶",
        "teacher": "教師",
        "blowjob": "口交",
        "gaping": "穴擴張",
        "lioness": "母獅",
        "panther": "豹子",
        "eyemask": "眼罩",
        "reptile": "爬行",
        "smoking": "吸煙",
        "gyaru": "日式太妹",
        "ishikei": "石惠",
        "crotch=": "襠部",
        "nipples": "乳頭",
        "costume": "服飾",
        "western": "西方",
        "gigantic": "巨大",
        "no bra": "沒有胸罩",
        "cowman": "男奶牛人",
        "femdom": "女性支配",
        "balljob": "睪丸交",
        "corset": "緊身胸衣",
        "cowgirl": "奶牛娘",
        "growth": "體型增大",
        "hairjob": "髮絲交",
        "syringe": "注射器",
        "pegging": "女插男",
        "sarashi": "纏胸布",
        "omorashi": "憋尿",
        "vtuber": "虛擬主播",
        "abortion": "墮胎",
        "bandages": "繃帶",
        "bandaid": "創可貼",
        "big ass": "大屁股",
        "cashier": "收銀員",
        "centaur": "半人馬",
        "cheating": "出軌",
        "daughter": "女兒",
        "dinosaur": "恐龍",
        "dog girl": "狗娘",
        "ear fuck": "耳交",
        "elephant": "大象",
        "fox girl": "狐娘",
        "freckles": "雀斑",
        "futanari": "扶他",
        "gijinka": "擬人化",
        "haigure": "緊身衣",
        "kangaroo": "袋鼠",
        "leotard": "緊身衣",
        "machine": "性機器",
        "mermaid": "人魚娘",
        "swimsuit": "泳裝",
        "unicorn": "獨角獸",
        "vampire": "吸血鬼",
        "yukkuri": "慢慢的",
        "ponytail": "馬尾",
        "tickling": "撓癢",
        "lolicon": "蘿莉控",
        "sweating": "出汗",
        "tomgirl": "娘娘腔",
        "lingerie": "內衣",
        "pregnant": "懷孕",
        "sleeping": "睡覺",
        "phimosis": "包莖",
        "leg lock": "夾腿",
        "sumata": "股間性交",
        "piercing": "穿刺",
        "pig girl": "豬娘",
        "wormhole": "蟲洞",
        "unbirth": "反出生",
        "bee girl": "蜂娘",
        "eyepatch": "眼罩",
        "old man": "老男人",
        "onahole": "自慰器",
        "shotacon": "正太",
        "speculum": "窺器",
        "military": "軍服",
        "gyaru-oh": "輕浮男",
        "anaglyph": "浮雕",
        "koakuma": "小惡魔",
        "princess": "公主",
        "original": "原創",
        "art book": "畫集",
        "gamecg": "遊戲CG",
        "creature": "生物",
        "buttocks": "臀部",
        "violence": "暴力",
        "glasses": "戴眼鏡",
        "tanlines": "曬黑",
        "animated": "動畫",
        "textless": "無文字",
        "game cg": "遊戲CG",
        "image set": "圖集",
        "unsorted": "未分類",
        "yuri": "百合 (GL)",
        "yaoi": "男同 (BL)",
        "sister": "姐妹",
        "tailjob": "尾巴性交",
        "fundoshi": "兜襠布",
        "wolf boy": "男狼人",
        "gang rape": "輪姦",
        "imageset": "圖片集",
        "netorase": "NTR",
        "mesugaki": "雌小鬼",
        "smalldom": "小鬼頭",
        "petplay": "寵物遊戲",
        "hair buns": "髮髻",
        "fishnets": "漁網服",
        "widower": "喪偶男性",
        "bear boy": "熊男孩",
        "big clit": "大陰蒂",
        "big lips": "厚嘴唇",
        "bisexual": "雙性戀",
        "blackmail": "勒索",
        "bloomers": "燈籠褲",
        "bodysuit": "緊身衣",
        "caption": "自製標題",
        "cum bath": "精液浴",
        "gasmask": "防毒面罩",
        "giantess": "女巨人",
        "horse boy": "馬男",
        "netorare": "NTR",
        "nose fuck": "鼻交",
        "parasite": "寄生蟲",
        "sex toys": "性玩具",
        "sundress": "太陽裙",
        "tentacles": "觸手",
        "webtoon": "網路漫畫",
        "wrestling": "摔跤",
        "strap-on": "假陽具",
        "nakadashi": "中出",
        "squirting": "潮吹",
        "trampling": "踩踏",
        "minotaur": "牛頭人",
        "oyakodon": "母女丼",
        "lab coat": "實驗服",
        "tail plug": "肛塞",
        "non-nude": "非裸體",
        "snake boy": "蛇男",
        "wolf girl": "狼女",
        "pantyjob": "內褲交",
        "urination": "排尿",
        "skinsuit": "假外皮",
        "virginity": "處女",
        "lactation": "乳汁",
        "kunoichi": "女忍者",
        "cosplay": "角色扮演",
        "miniguy": "迷你男孩",
        "conjoined": "連體",
        "old lady": "老女人",
        "kigurumi": "玩偶服",
        "ponygirl": "女騎師",
        "bunny boy": "兔男",
        "anorexic": "厭食症",
        "tall man": "高男人",
        "mouse boy": "鼠男",
        "hardcore": "重口味",
        "replaced": "已更換",
        "valkyrie": "女武神",
        "leg locks": "腳鎖",
        "technical": "技術",
        "doujinshi": "同人誌",
        "ambiguous": "模糊的",
        "hotpants": "緊身短褲",
        "scanmark": "掃描標記",
        "swinging": "換性伴侶",
        "nose hook": "鉤鼻子",
        "pantyhose": "連褲襪",
        "policeman": "男員警",
        "spanking": "打屁股",
        "voyeurism": "偷窺狂",
        "stockings": "長筒襪",
        "cock ring": "陰莖環",
        "headphones": "耳機",
        "nijisanji": "彩虹社",
        "goudoushi": "新幹線",
        "mouth mask": "口罩",
        "shimaidon": "姐妹丼",
        "pixie cut": "精靈頭",
        "anthology": "精選集",
        "bear girl": "熊女孩",
        "bestiality": "獸奸",
        "big balls": "大睪丸",
        "big penis": "大陰莖",
        "catfight": "兩女相爭",
        "chloroform": "迷藥",
        "corruption": "墮落",
        "cum swap": "交換口交",
        "cuntboy": "有穴的男人",
        "dakimakura": "抱枕",
        "frog girl": "青蛙娘",
        "frottage": "陰莖擊劍",
        "glory hole": "牆穴",
        "horse cock": "馬屌",
        "horse girl": "馬娘",
        "kemonomimi": "獸耳",
        "mecha boy": "機甲男",
        "rhinoceros": "犀牛",
        "tracksuit": "運動服",
        "twintails": "雙馬尾",
        "underwater": "水下",
        "waitress": "女服務員",
        "plant boy": "植物男",
        "tankoubon": "單行本",
        "shimapan": "條紋胖次",
        "invisible": "隱形人",
        "possession": "佔據",
        "snake girl": "蛇女",
        "selfcest": "自我性交",
        "prolapse": "子宮脫垂",
        "minigirl": "迷你女孩",
        "low scat": "隱晦排糞",
        "dark skin": "黑皮膚",
        "deepthroat": "深喉",
        "paperchild": "紙孩",
        "plant girl": "植物",
        "sheep boy": "男羊人",
        "artistcg": "繪師CG",
        "tall girl": "高個女",
        "stretching": "伸展",
        "mouse girl": "鼠娘",
        "demon girl": "女妖",
        "plant guy": "植物男",
        "snake guy": "男蛇人",
        "schoolboy": "男學生",
        "daiyousei": "大妖精",
        "discipline": "調教",
        "bunny ears": "兔耳",
        "lower body": "下身",
        "disability": "殘疾",
        "psssession": "佔據",
        "themeless": "無主題",
        "realporn": "真實色情",
        "speechless": "無文字",
        "artist cg": "畫師CG",
        "blindfold": "矇住眼睛",
        "christmas": "聖誕服裝",
        "sunglasses": "太陽鏡",
        "full color": "全彩色",
        "high heels": "高跟鞋",
        "facial hair": "鬍子",
        "big vagina": "大陰道",
        "body swap": "身體交換",
        "bunny girl": "兔女郎",
        "coprophagia": "食糞",
        "defloration": "破處",
        "dismantling": "拆解",
        "grandfather": "祖父",
        "grandmother": "祖母",
        "asian porn": "亞洲色情",
        "gymshorts": "拳擊短褲",
        "kneepit sex": "膝交",
        "navel fuck": "肚臍交",
        "real doll": "充氣娃娃",
        "time stop": "時間停止",
        "wet clothes": "濕身",
        "story arc": "故事框架",
        "screenshots": "截圖",
        "shrinking": "體型縮小",
        "masked face": "面具",
        "humiliation": "淩辱",
        "shark boy": "鯊魚男孩",
        "squid boy": "魷魚男孩",
        "human pet": "人類寵物",
        "sheep girl": "綿羊娘",
        "tribadism": "女同性戀",
        "uncensored": "無修正",
        "shaved head": "平頭",
        "inflation": "胃區膨脹",
        "layer cake": "換著插",
        "fingering": "手指撥弄",
        "sole male": "唯一男性",
        "handicapped": "殘疾",
        "insect boy": "昆蟲男",
        "lizard guy": "蜥蜴男",
        "squid girl": "魷魚娘",
        "slime boy": "史萊姆男",
        "facesitting": "坐臉",
        "toddlercon": "嬰兒控",
        "robot girl": "機器娘",
        "schoolgirl": "女學生",
        "school boy": "男學生",
        "guys only": "只有男性",
        "sex addict": "性成癮",
        "incomplete": "不完整",
        "hidden sex": "隱藏性愛",
        "cum in eye": "射在眼精",
        "absorption": "吞噬吸收",
        "armpit sex": "腋下性愛",
        "brain fuck": "入腦性交",
        "cosplaying": "角色扮演",
        "cunnilingus": "舔陰部",
        "mecha girl": "機甲少女",
        "public use": "公眾使用",
        "race queen": "賽車女郎",
        "policewoman": "女員警",
        "long tongue": "長舌頭",
        "phone sex": "打電話性交",
        "cuntbusting": "穴侵犯",
        "analphagia": "文字缺失",
        "tailphagia": "尾巴吞噬",
        "big muscles": "大肌肉",
        "variant set": "差分圖",
        "small penis": "小陰莖",
        "focus anal": "專注肛門",
        "watermarked": "浮水印",
        "soushuuhen": "長篇合集",
        "cumflation": "累積膨脹",
        "big breasts": "大乳房",
        "anal birth": "肛門出產",
        "asphyxiation": "窒息",
        "big areolae": "大乳暈",
        "big nipples": "大乳頭",
        "foot licking": "舔足",
        "garter belt": "吊帶襪",
        "menstruation": "經血",
        "josou seme": "女裝攻方",
        "masturbation": "自慰",
        "prostitution": "賣淫",
        "nipple fuck": "乳頭交",
        "necrophilia": "戀屍癖",
        "nudity only": "僅裸體",
        "stewardess": "女乘務員",
        "males only": "只有男性",
        "oppai loli": "巨乳蘿莉",
        "panda girl": "熊貓女孩",
        "shark girl": "鯊魚女孩",
        "huge penis": "巨大陰莖",
        "infantilism": "幼稚病",
        "mind break": "精神受創",
        "insect girl": "昆蟲娘",
        "lizard girl": "蜥蜴娘",
        "wooden horse": "木馬",
        "alien girl": "外星女孩",
        "motorboating": "埋胸",
        "interracial": "跨種族",
        "animal ears": "動物耳朵",
        "metal armor": "金屬盔甲",
        "weight gain": "體重增加",
        "randoseru": "日式小學書包",
        "kodomo only": "僅有兒童",
        "sketch lines": "素描線",
        "large tattoo": "大紋身",
        "drill hair": "大小姐鑽頭",
        "beauty mark": "美麗印記",
        "autopaizuri": "自己乳交",
        "blowjob face": "口交臉",
        "bodystocking": "連身襪",
        "cannibalism": "同類相食",
        "cheerleader": "啦啦隊長",
        "chinese dress": "旗袍",
        "clit growth": "陰蒂增長",
        "closed eyes": "閉著眼睛",
        "dark sclera": "深色眼白",
        "dick growth": "陰莖生長",
        "dicknipples": "陰莖乳頭",
        "doll joints": "球形關節",
        "double anal": "肛門雙交",
        "feminization": "男變女",
        "forniphilia": "人型家居",
        "game sprite": "畫素畫面",
        "granddaughter": "孫女",
        "petrification": "石化",
        "pole dancing": "鋼管舞",
        "piss drinking": "喝尿",
        "penis birth": "陰莖分娩",
        "raccoon boy": "浣熊男孩",
        "spider girl": "蜘蛛女孩",
        "slime girl": "史萊姆女孩",
        "triple anal": "肛門三插",
        "sole female": "唯一女性",
        "dark nipples": "黑乳頭",
        "raccoon girl": "浣熊娘",
        "solo action": "獨自愉悅",
        "business suit": "西裝",
        "netonare": "NTR 綠帽子",
        "cockslapping": "陰莖蹭臉",
        "huge breasts": "巨大乳房",
        "monster girl": "怪物女孩",
        "ai generated": "AI生成",
        "futanarization": "扶他",
        "missing cover": "無封面",
        "painted nails": "指甲油",
        "poor grammar": "語義不通",
        "gender morph": "性別變換",
        "autofellatio": "自己口交",
        "ball sucking": "吮吸睪丸",
        "bike shorts": "腳踏車短褲",
        "body writing": "人體寫作",
        "chastity belt": "貞操帶",
        "exhibitionism": "暴露狂",
        "females only": "僅有女性",
        "gender bender": "性轉換",
        "hairy armpits": "多腋毛",
        "heterochromia": "異色瞳",
        "magical girl": "魔法少女",
        "pubic stubble": "陰毛渣",
        "mind control": "精神控製",
        "small breasts": "小乳房",
        "tooth brushing": "刷牙",
        "nipple birth": "乳頭分娩",
        "human cattle": "人型牲畜",
        "stuck in wall": "卡牆裡",
        "low lolicon": "隱晦蘿莉控",
        "transformation": "轉化",
        "out of order": "順序顛倒",
        "ari and mura": "阿里和穆拉",
        "multiple arms": "多個手臂",
        "kodomo doushi": "兒童教學",
        "focus paizuri": "專注乳交",
        "vaginal birth": "陰道分娩",
        "gender change": "性別轉換",
        "thick eyebrows": "濃眉毛",
        "ass expansion": "屁股膨脹",
        "body painting": "人體彩繪",
        "crotch tattoo": "胯部紋身",
        "electric shocks": "電擊",
        "eye penetration": "眼交",
        "foot insertion": "腳插入",
        "muscle growth": "肌肉增長",
        "shared senses": "感官共享",
        "orgasm denial": "絕頂禁止",
        "squirrel girl": "松鼠女孩",
        "living clothes": "活衣服",
        "sole dickgirl": "唯一扶他",
        "very long hair": "長頭髮",
        "focus blowjob": "專注口交",
        "no penetration": "無插入",
        "double vaginal": "雙陰道",
        "low shotacon": "隱晦正太控",
        "triple vaginal": "三陰道",
        "crossdressing": "穿異性服裝",
        "breast feeding": "母乳餵食",
        "armpit licking": "腋下舔",
        "ttt threesome": "扶他三人組",
        "rough grammar": "粗略的語法",
        "fff threesome": "女性三人組",
        "stirrup legwear": "馬鐙褲",
        "mmm threesome": "男性三人組",
        "anal intercourse": "肛交",
        "age regression": "返老還童",
        "dickgirls only": "全都扶他",
        "double blowjob": "雙人口交",
        "emotionless sex": "性冷感",
        "gothic lolita": "歌德式蘿莉",
        "stereoscopic": "立體視覺影象",
        "low bestiality": "隱晦獸交",
        "impregnation": "性行為後懷孕",
        "unusual teeth": "不尋常的牙齒",
        "vaginal sticker": "陰部貼紙",
        "apparel bukkake": "著裝顏射",
        "nipple piercing": "乳頭穿孔",
        "forced exposure": "強制暴露",
        "ffm threesome": "女女男三人組",
        "mmf threesome": "男男女三人組",
        "age progression": "快速長大",
        "balls expansion": "睪丸膨脹",
        "clothed paizuri": "著裝乳交",
        "full censorship": "全馬賽克",
        "gigantic breasts": "超巨乳",
        "prehensile hair": "抓著頭髮",
        "school swimsuit": "學校泳裝",
        "thigh high boots": "長筒靴",
        "mosaic censorship": "有碼",
        "scrotal lingerie": "陰囊袋",
        "human on furry": "人類和獸人",
        "multiple vaginas": "多陰道",
        "multiple nipples": "多乳頭",
        "extraneous ads": "無關的廣告",
        "completely nude": "完全裸體",
        "unusual pupils": "不尋常的瞳孔",
        "multiple penises": "多個陰莖",
        "multiple paizuri": "多人乳交",
        "cervix prolapse": "子宮頸脫垂",
        "clit stimulation": "陰蒂刺激",
        "domination loss": "統治權喪失",
        "multiple orgasms": "多重高潮",
        "animal on animal": "動物性交",
        "breast expansion": "乳房膨脹",
        "breast reduction": "乳房縮小",
        "full body tattoo": "全身紋身",
        "large insertions": "巨物插入",
        "nipple expansion": "乳頭膨脹",
        "inverted nipples": "乳頭內陷",
        "multiple breasts": "多個乳房",
        "genital piercing": "生殖器穿孔",
        "penis enlargement": "陰莖增大",
        "detached sleeves": "分離式袖子",
        "rough translation": "粗略翻譯",
        "exposed clothing": "暴露的衣服",
        "eye-covering bang": "遮眼瀏海",
        "fft threesome": "兩女一扶他三人組",
        "mmt threesome": "二男一扶他三人組",
        "ttf threesome": "二扶他一女三人組",
        "ttm threesome": "二扶他一男三人組",
        "multi-work series": "故事系列",
        "body modification": "身體改造",
        "dickgirl on male": "扶他與男性",
        "prostate massage": "前列腺按摩",
        "urethra insertion": "尿道插入",
        "male on dickgirl": "男性與扶他",
        "school gym uniform": "體操服",
        "moral degeneration": "道德淪喪",
        "unusual insertions": "異物插入",
        "multimouth blowjob": "多重口交",
        "nipple stimulation": "乳頭刺激",
        "double penetration": "雙洞插入",
        "table masturbation": "桌子自慰",
        "schoolboy uniform": "男學生制服",
        "triple penetration": "三人互插",
        "cervix penetration": "子宮頸透視",
        "internal urination": "身體內排尿",
        "personality excretion": "排洩",
        "multipanel sequence": "多幀序列",
        "mtf threesome": "一男一女一扶他三人組",
        "adventitious penis": "不確定陰莖",
        "all the way through": "全身貫穿",
        "schoolgirl uniform": "女學生制服",
        "stomach deformation": "胃部突起",
        "forbidden content": "禁止內容",
        "dickgirl on female": "扶他對多女性",
        "adventitious vagina": "不確定陰道",
        "transparent clothing": "透明衣服",
        "dickgirl on dickgirl": "扶他與扶他",
        "kindergarten uniform": "幼兒園制服",
        "full-packaged futanari": "全都扶他",
        "first person perspective": "第一人稱",
        "clothed male nude female": "穿衣男 裸體女",
        "clothed female nude male": "穿衣女 裸體男",
    };

    // 合併成單詞表 (優先度越高的越後面, 因為後添加會覆蓋前面重複的)
    const All_Words = Object.assign(Short_Words, Long_Words, Language, Artist, Character, Title, Beautify, Tags);

    const Syntax = (()=> {
        function Debounce(func, delay=100) {
            let timer = null;
            return (...args) => {
                clearTimeout(timer);
                timer = setTimeout(function() {
                    func(...args);
                }, delay);
            }
        };

        async function WaitElem(selector, found) {
            const observer = new MutationObserver(Debounce(() => {
                const element = document.querySelector(selector);
                if (element) {
                    observer.disconnect();
                    found(element);
                }
            }));

            observer.observe(document, {
                subtree: true,
                childList: true,
                attributes: true,
                characterData: true
            });
        };

        function getTextNodes(root) {
            const tree = document.createTreeWalker( // 過濾出所有可用 文字節點
                root,
                NodeFilter.SHOW_TEXT,
                {
                    acceptNode: (node) => {
                        const content = node.nodeValue.trim();
                        return content == '' || !/[\w\p{L}]/u.test(content)
                        ? NodeFilter.FILTER_REJECT
                        : NodeFilter.FILTER_ACCEPT;
                    }
                }
            );

            let node;
            const nodes = [];
            while (node = tree.nextNode()) {
                nodes.push(node);
            }
            return nodes;
        };

        async function Transform(textNode) {
            textNode.textContent =
            textNode.textContent.replace(/[\p{L}]+(?:[^()\[\]{}\t])+[\p{L}]\.*/gu,
            content => All_Words[content.toLowerCase()] ?? content);
            textNode.textContent =
            textNode.textContent.replace(/[\p{L}]+/gu,
            content => All_Words[content.toLowerCase()] ?? content); // 翻譯個別單字 (例外狀況)
        };

        return {
            Debounce,
            WaitElem,
            Translator: async (root) => { // 當需要遍歷多個節點
                getTextNodes(root).forEach(textNode => Transform(textNode));
            },
        }
    })();

    Syntax.WaitElem("body", body => {
        Syntax.Translator(body); // 開始立即觸發

        let mutation; // 監聽後續變化
        const observer = new MutationObserver(Syntax.Debounce((mutationsList, observer) => {
            for (mutation of mutationsList) {
                if (mutation.type === 'childList' || mutation.type === 'characterData') {
                    Syntax.Translator(body);
                    break;
                }
            }
        }, 200));

        observer.observe(document.body, {
            subtree: true,
            childList: true,
        });
    });
})();